### ISSUE TITLE
climate.turn_on and climate.turn_off do no longer work

### ISSUE THREAD

**Issue by Ra72xx** [jmcollin78/versatile_thermostat#419]
I recently noticed that my automations do no longer work. I can't pinpoint exactly since when, it must be only since a few releases. The reason is that the functions "climate.turn_on" and "climate.turn_off" are available, but do no longer work, at least for my virtual versatile thermostats regulating real Aqara thermostats. They result in:
`websocket_api script: Error executing script. Unexpected error for call_service at pos 1: type object 'HVACMode' has no attribute 'HEATING'
`
The function "climate.set_hvac_mode" still seems to work, however.

**Comment by cazzzimir** [comment]
Yep ! I confirm ! got same issue ! I've just upgraded to 6.0.1 / was working on 5.0.4

**Comment by sleveille4** [comment]
hi, ran into the same issue with automation and climate entities, but not limited to versatile thermostat.

i assumed it had to do with HA update (deprecating this? ) and i replaced the generic turn off / turn on i used previously wich no longer work with climate.set_temperature or climate.set_hvac_mode sending "heat" or "off"

climate.set_temperature allows to control hvac mode and set a target temp at the same time

**Comment by jmcollin78** [comment]
I have fixed the issue but not published yet. It will come soon

**Comment by sleveille4** [comment]
just wanted to share my experience as since it is not limited to versatile, and i found a working alternative, it would help :)

**Comment by jmcollin78** [comment]
https://github.com/jmcollin78/versatile_thermostat/releases/tag/6.0.2
